<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
    $IP = MW_INSTALL_PATH;
} else {
    $IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
    if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
        die( "This script must be run from the command line\n" );
    }
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "DeuterosX.org";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath       = "/mediawiki";
$wgScriptExtension  = ".php";

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "achton@netherclift.net";
$wgPasswordSender = "achton@netherclift.net";

## For a detailed description of the following switches see
## http://www.mediawiki.org/wiki/Extension:Email_notification
## and http://www.mediawiki.org/wiki/Extension:Email_notification
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "dbname";
$wgDBuser           = "dbuser";
$wgDBpassword       = "dbpassword";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "TYPE=InnoDB";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "ffcc1a8be1a51c34fe8a2dc02f75b1e85753f0a8fc16bd9815d94c04f375c4cb";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'deuteros';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );


$wgUseAjax = true;
$wgAjaxSearch = true;
$wgSkipSkins = array( "chick", "cologneblue", "modern", "myskin", "monobook", "nostalgia", "simple", "standard" );

// ******************************************************
// Pretty URLS
// ******************************************************
$wgScriptPath = '/mediawiki';         # Path to the actual files. This should already be there
$wgArticlePath = '/wiki/$1';  # Virtual path. This directory MUST be different from the one used in $wgScriptPath
$wgUsePathInfo = true;


// ******************************************************
// CUSTOM NAMESPACE
// ******************************************************
define('NS_DEUTEROSX', 100);
define('NS_DEUTEROSX_TALK', 101);
define('NS_DEUTEROS', 102);
define('NS_DEUTEROS_TALK', 103);

$wgExtraNamespaces[NS_DEUTEROSX]        = 'DeuterosX';
$wgExtraNamespaces[NS_DEUTEROSX_TALK]   = 'DeuterosX_talk';
$wgExtraNamespaces[NS_DEUTEROS]         = 'Deuteros';
$wgExtraNamespaces[NS_DEUTEROS_TALK]    = 'Deuteros_talk';


#Set default searching/*
$wgNamespacesToBeSearchedDefault = array(
        NS_MAIN =>           true,
        NS_TALK =>           true,
        NS_USER =>           true,
        NS_USER_TALK =>      true,
        NS_PROJECT =>        true,
        NS_PROJECT_TALK =>   true,
        NS_IMAGE =>          true,
        NS_IMAGE_TALK =>     false,
        NS_MEDIAWIKI =>      false,
        NS_MEDIAWIKI_TALK => false,
        NS_TEMPLATE =>       false,
        NS_TEMPLATE_TALK =>  false,
        NS_HELP =>           false,
        NS_HELP_TALK =>      false,
        NS_CATEGORY =>       true,
        NS_CATEGORY_TALK =>  true,
        NS_DEUTEROSX  =>     true,
        NS_DEUTEROSX_TALK => true,
        NS_DEUTEROS  =>      true,
        NS_DEUTEROS_TALK =>  true,
);

// ******************************************************
// PHPBB User Database Plugin. (Requires MySQL Database)
// ******************************************************
require_once ($IP . '/extensions/Auth_phpBB.php');

$wgAuth_Config = array(); // Clean.

// Name of your PHPBB group
// users need to be a member
// of to use the wiki. (i.e. wiki)
// This can also be set to an array
// of group names to use more then
// one. (ie.
// $wgAuth_Config['WikiGroupName'][] = 'Wiki';
// $wgAuth_Config['WikiGroupName'][] = 'Wiki2';
// or
// $wgAuth_Config['WikiGroupName'] = array('Wiki', 'Wiki2');
// )
$wgAuth_Config['WikiGroupName'] = array('Deuteros Wiki Editors', 'Deuteros PC Design Team');

$wgAuth_Config['UseWikiGroup'] = true;          // This tells the Plugin to require
                                                // a user to be a member of the above
                                                // phpBB group. (ie. wiki) Setting
                                                // this to false will let any phpBB
                                                // user edit the wiki.

$wgAuth_Config['UseExtDatabase'] = true;        // This tells the plugin that the phpBB tables
                                                // are in a different database then the wiki.
                                                // The default settings is false.

$wgAuth_Config['MySQL_Host']        = 'localhost';      // phpBB MySQL Host Name.
$wgAuth_Config['MySQL_Username']    = 'dbuser';         // phpBB MySQL Username.
$wgAuth_Config['MySQL_Password']    = 'dbpassword';     // phpBB MySQL Password.
$wgAuth_Config['MySQL_Database']    = 'dbname';         // phpBB MySQL Database Name.

$wgAuth_Config['UserTB']         = 'phpbb3_users';      // Name of your PHPBB user table. (i.e. phpbb_users)
$wgAuth_Config['GroupsTB']       = 'phpbb3_groups';     // Name of your PHPBB groups table. (i.e. phpbb_groups)
$wgAuth_Config['User_GroupTB']   = 'phpbb3_user_group'; // Name of your PHPBB user_group table. (i.e. phpbb_user_group)
$wgAuth_Config['PathToPHPBB']    = '../forum/';         // Path from this file to your phpBB install.

// Local
$wgAuth_Config['LoginMessage']   = '<b>You need an account to login.</b><br /><a href="' . $wgAuth_Config['PathToPHPBB'] .
                                   'ucp.php?mode=register">Click here to create an account.</a>'; // Localize this message.
$wgAuth_Config['NoWikiError']    = 'You do not have permission to access this page.'; // Localize this message.

$wgAuth = new Auth_phpBB($wgAuth_Config);     // Auth_phpBB Plugin.

// ******************************************************
// LOCKDOWN
// ******************************************************
require_once ($IP . '/extensions/Lockdown.php');
require_once ($IP . '/extensions/Auth_phpBB_Groups.php');

/* Special permissions */
$wgGroupPermissions['Deuteros PC Design Team']['editinterface'] = true;

/* Read-only namespaces */
$wgNamespacePermissionLockdown[NS_MAIN]['edit'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_MAIN]['move'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_TALK]['edit'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_TALK]['move'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_PROJECT]['edit'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_PROJECT]['move'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_PROJECT_TALK]['edit'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_PROJECT_TALK]['move'] = array('Deuteros PC Design Team');

/* Read/write namespaces (for the wiki team) */
// (implicitly gives the wiki group full access)
// NS_USER
// NS_USER_TALK
// NS_DEUTEROS
// NS_DEUTEROS_TALK
// NS_IMAGE
// NS_IMAGE_TALK
// NS_TEMPLATE
// NS_TEMPLATE_TALK
// NS_HELP
// NS_HELP_TALK
// NS_CATEGORY
// NS_CATEGORY_TALK

/* No-access namespaces (only Deuteros team may access) */
$wgNamespacePermissionLockdown[NS_MEDIA]['*'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_SPECIAL]['*'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_MEDIAWIKI]['*'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_MEDIAWIKI_TALK]['*'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_DEUTEROSX]['*'] = array('Deuteros PC Design Team');
$wgNamespacePermissionLockdown[NS_DEUTEROSX_TALK]['*'] = array('Deuteros PC Design Team');

/*

        NS_MEDIA            => 'Media',
        NS_SPECIAL          => 'Special',
        NS_MAIN             => '',
        NS_TALK             => 'Talk',
        NS_USER             => 'User',
        NS_USER_TALK        => 'User_talk',
        NS_WIKIPEDIA        => $wgMetaNamespace,
        NS_WIKIPEDIA_TALK   => $wgMetaNamespace . '_talk',
        NS_IMAGE            => 'Image',
        NS_IMAGE_TALK       => 'Image_talk',
        NS_MEDIAWIKI        => 'MediaWiki',
        NS_MEDIAWIKI_TALK   => 'MediaWiki_talk',
        NS_TEMPLATE         => 'Template',
        NS_TEMPLATE_TALK    => 'Template_talk',
        NS_HELP             => 'Help',
        NS_HELP_TALK        => 'Help_talk',
        NS_CATEGORY         => 'Category',
        NS_CATEGORY_TALK    => 'Category_talk'
*/

?>
